// Copied verbatim from app/src/lib/matching/constants.ts. The scraper is a
// separate bounded context and must NOT import from app/, so these vocabularies
// are duplicated here on purpose. Keep in sync manually if the app's lists change.

export const TAGS = [
  "sport",
  "giovani",
  "scuola",
  "inclusione",
  "disabilità",
  "anziani",
  "salute",
  "outdoor",
  "welfare",
  "comunità",
  "rigenerazione urbana",
  "turismo",
  "volontariato",
  "ambiente",
  "formazione",
  "pari opportunità",
  "eventi",
  "centri estivi",
  "NEET",
  "famiglie",
  "impianti sportivi",
  "povertà educativa",
  "terzo settore",
  "co-progettazione",
  "quartieri",
  "prevenzione",
  "benessere",
  "cultura",
  "digitale",
  "innovazione",
  "occupazione",
  "educazione",
  "sostenibilità",
  "salute mentale",
  "migranti",
  "donne",
  "minori",
  "periferie",
  "servizio civile",
  "capacity building",
  "innovazione sociale",
  "housing sociale",
  "disagio giovanile",
  "contrasto povertà",
  "accessibilità",
  "comunità educante",
  "comunità educanti",
] as const;

export const LEGAL_TYPES = [
  "ASD - Associazione Sportiva Dilettantistica",
  "SSD - Società Sportiva Dilettantistica",
  "SSD a r.l. - Società Sportiva Dilettantistica a responsabilità limitata",
  "ASD/SSD iscritta RASD",
  "EPS - Ente di Promozione Sportiva",
  "FSN - Federazione Sportiva Nazionale",
  "DSA - Disciplina Sportiva Associata",
  "AB - Associazione Benemerita",
  "Comitato territoriale EPS/FSN",
  "Società sportiva professionistica",
  "Associazione non riconosciuta",
  "Associazione riconosciuta",
  "APS - Associazione di Promozione Sociale",
  "ODV - Organizzazione di Volontariato",
  "ETS - Ente del Terzo Settore",
  "Rete associativa ETS",
  "Ente filantropico",
  "Società di mutuo soccorso",
  "ONLUS",
  "ONG / OSC",
  "Cooperativa sociale tipo A",
  "Cooperativa sociale tipo B",
  "Consorzio di cooperative sociali",
  "Impresa sociale",
  "Fondazione ETS",
  "Fondazione di comunità",
  "Fondazione di origine bancaria",
  "Fondazione privata",
  "Fondazione pubblica",
  "Comitato",
  "Comitato organizzatore",
  "Pro Loco",
  "Ente ecclesiastico civilmente riconosciuto",
  "Parrocchia / Oratorio",
  "Ente religioso",
  "Comune",
  "Unione di Comuni",
  "Provincia / Città Metropolitana",
  "Regione",
  "Azienda pubblica di servizi alla persona",
  "Azienda sanitaria / AUSL",
  "Istituto scolastico statale",
  "Istituto scolastico paritario",
  "Università",
  "Centro di ricerca",
  "Ente di formazione accreditato",
  "Ente pubblico",
  "Ente locale",
  "Soggetto gestore impianto sportivo",
  "Gestore centro sportivo",
  "Impresa",
  "PMI",
  "Start-up innovativa",
  "Società benefit",
  "Associazione di categoria",
  "Camera di Commercio",
  "Sindacato / organizzazione datoriale",
  "Gruppo informale",
  "Raggruppamento temporaneo / ATS",
  "Partner tecnico",
  "Partner istituzionale",
  "Altro",
] as const;

export const DOCUMENT_KEYS = ["statuto", "bilancio", "runts", "rasd", "durc", "certificazioni"] as const;
export const GEO_SCOPES = ["comunale", "provinciale", "regionale", "nazionale", "europeo"] as const;
export const COMPLEXITY = ["bassa", "media", "alta"] as const;
export const GRANT_STATUS = ["aperto", "chiuso"] as const;

export const TAG_SET = new Set<string>(TAGS);
export const LEGAL_TYPE_SET = new Set<string>(LEGAL_TYPES);
export const DOCUMENT_KEY_SET = new Set<string>(DOCUMENT_KEYS);
export type GeoScope = (typeof GEO_SCOPES)[number];
export type Complexity = (typeof COMPLEXITY)[number];
export type GrantStatus = (typeof GRANT_STATUS)[number];
